# Generated by cucumber-sinatra. (2013-05-07 14:22:58 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/hawkerboard.rb')

require 'capybara'
require 'capybara/cucumber'
require 'capybara-webkit'
require 'rspec'
require 'rack/test'

Capybara.app = Hawkerboard
Capybara.javascript_driver = :webkit

class HawkerboardWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  HawkerboardWorld.new
end
